# Generated by Django 5.0.4 on 2024-05-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='ocupied',
            new_name='occupied',
        ),
    ]
