# Generated by Django 5.0.4 on 2024-05-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_reservation_name_reservation_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
