# Generated by Django 5.0.4 on 2024-05-06 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_rename_ocupied_room_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='Hotel.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(unique=True),
        ),
    ]
