# Generated by Django 5.0.4 on 2024-06-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_alter_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='television',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
