# Generated by Django 5.0.4 on 2024-06-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('Single', 'Single'), ('Suite', 'Suite'), ('Double', 'Double')], max_length=50),
        ),
    ]
