# Generated by Django 5.0.4 on 2024-06-05 09:57

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_room_num_beds_room_num_toilets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='location',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='metodo_pago',
            old_name='opcion_pago',
            new_name='payment_type',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='ninos',
            new_name='children',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='ninos',
            new_name='children',
        ),
        migrations.AddField(
            model_name='customuser',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('NIE', 'NIE'), ('DNI', 'DNI')], default='PASSPORT', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='CountryField',
            field=django_countries.fields.CountryField(default='Spain', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nationality',
            field=django_countries.fields.CountryField(default='Spain', max_length=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=3),
        ),
    ]
